In [1]:
import numpy as np
#numpy에다가 별칭을 붙여줌
#ndarray클래스
#다차원 행렬 자료 구조를 지원하는 클래스
#내부 반복문을 사용해서 속도가 빠르다
#배열 간에 산술 연산이 가능하다
#다차원 배열은 입체적인 구조를 지닌다

data = [1,2,3]

a = np.array(data)
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [2]:
a =np.array([i for i in range(2, 11, 2)]) #range(start, stop,step)
a

array([ 2,  4,  6,  8, 10])

In [3]:
print(np.arange(10)) #np.arange(start.stop.step)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
#어떤 메소드가 있는지 보여준다.
dir(a)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__

In [7]:
a=np.arange(10)
#.shape : 배열의 모양을 찾습니다.
#.ndim: 몇 차원인지 말해주다.
# .size : 배열 안에 값의 크기를 말합니다.


In [8]:
data = [1,2,3]

a= np.arrat(data)
a.dtype


AttributeError: ignored

In [11]:
data = [1,2,3]

a = np.array(data, dtype=np.float64)
a.dtype

dtype('float64')

In [12]:
data = [1.1,2,3]
a=np.array(data)
print(a)

a = np.int32(a)
print(a)

[1.1 2.  3. ]
[1 2 3]


In [13]:
#0차원
a = np.array(1)


In [14]:
#1차원 (Vector)숫자들의 배열
a= np.array([1,2,3])


In [15]:
#2 차원
a = np.array([[1,2,3],[1,2,3],[1,2,3]])
print(a)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [16]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
a[2]

2

In [19]:
a = np.arange(12),reshape(3,4)
a
#reshap와 arrange의 개수가 같아야 함

NameError: ignored

In [23]:
#3차원 배열 생성
 a = np.arange(40), reshape(2,5,4)
 a

IndentationError: ignored

In [24]:
[ ] a = np.arange(12),reshape(3,4)
 

SyntaxError: ignored

In [25]:
#조건 : ~(not)
#ex) if( ~(a==1))

In [32]:
a = np.arange(100).reshape(10,10)
a[2,2] = 500
a[1,1]= 100
print(a[4][5])
a

45


array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
       [ 10, 100,  12,  13,  14,  15,  16,  17,  18,  19],
       [ 20,  21, 500,  23,  24,  25,  26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
       [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
       [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
       [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]])

In [34]:
a = np.arange(30)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [36]:
a[5:20:2]

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [38]:
a = np.arange(12).reshape(3,4)
a
b=np.ones([3][4])
b


IndexError: ignored